config/routes.rb
GithubApi::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match "stars" => 'stars#create', :via => [:post]
  match "stars" => 'stars#destroy', :via => [:delete]

  match "/github/callback" => "sessions#callback"

  match "/my/starred_repos" => "my#starred_repos"
  match "/my/recommendations" => "my#recommendations"

  resources :search

  root :to => "home#index"
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
end

app/models/starred_repository.rb
class StarredRepository < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :registerable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name
  # attr_accessible :title, :body

  has_many :starred_repositories
  has_many :recommendations

  def self.find_for_github_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.create({name: auth.extra.raw_info.name, provider: auth.provider, uid: auth.uid, token: auth.credentials.token, login: auth.extra.raw_info.login}, without_protection: true)
    else
      user.update_attributes({token: auth.credentials.token, name: auth.extra.raw_info.name, login: auth.extra.raw_info.login}, without_protection: true)
    end
    user
  end

  def gather_starred_repos_from_github
    Github.new(oauth_token: self.token).activity.starring.starred(per_page: 1000)
  end

  def create_or_update_starred_repositories!
    starred_repos = gather_starred_repos_from_github
    starred_repos.each do |starred|
      repo = self.starred_repositories.where(full_name: starred.full_name).first_or_create
      repo.update_attributes({repo_name: starred.name, owner: starred.owner.login, owner_avatar_url: starred.owner.avatar_url, description: starred.description, language: starred.language, homepage: starred.homepage, html_url: starred.html_url}, without_protection: true)
    end
    destroy_repos_not_in!(starred_repos)
  end

  def destroy_repos_not_in!(starred_repos)
    self.starred_repositories.where("full_name not in (?)", starred_repos.map(&:full_name)).destroy_all
  end

  def star(user, repo)
    Github.new(oauth_token: self.token).activity.starring.star(user, repo)
    create_or_update_starred_repositories!
  end

  def unstar(user, repo)
    Github.new(oauth_token: self.token).activity.starring.unstar(user, repo)
    create_or_update_starred_repositories!
  end

  def needs_recommendations?
    self.recommendations_generated_at.blank? ||
    (self.recommendations_generated_at.present? &&
      ((Time.now-self.recommendations_generated_at)/1.hour) > 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  before_filter :mailer_set_url_options

  def mailer_set_url_options
    ActionMailer::Base.default_url_options[:host] = request.host_with_port
  end

  def github
    @github ||= Github.new
  end

  def authenticated_github
    if user_signed_in?
      @authenticated_github ||= Github.new(oauth_token: current_user.token)
    else
      nil
    end
  end
  helper_method :authenticated_github
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
  end
end

app/controllers/my_controller.rb
class MyController < ApplicationController
  def starred_repos
    current_user.create_or_update_starred_repositories!
    @starred_repos = current_user.starred_repositories
    respond_to do |format|
      format.js
      format.html
    end
  end

  def recommendations
    if current_user.needs_recommendations?
      @generating_new_recommendations
      current_user.update_column(:recommendations_generated_at, Time.now)
      Resque.enqueue(RecommendationEngine, current_user.id)
    end
    @recommendations = current_user.recommendations
    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_filter :authenticate_user!

  def github
    @user = User.find_for_github_oauth(request.env["omniauth.auth"], current_user)
    sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    current_user.create_or_update_starred_repositories!
    set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_filter :authenticate_user!
  def index
    if params[:keywords]
      @repos = github.search.repositories(keyword: Rack::Utils.escape(params[:keywords]), language: params[:language])
      if user_signed_in?
        @starred_repos = current_user.starred_repositories
      end
    end
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  def create
    @user_name = params[:user_name]
    @repo_name = params[:repo_name]
    current_user.star(params[:user_name], params[:repo_name])
  end

  def destroy
    @user_name = params[:user_name]
    @repo_name = params[:repo_name]
    current_user.unstar(params[:user_name], params[:repo_name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_helper.rb
module MyHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/views/home/index.html.erb
<h1>Welcome to the Github Programming Demo App</h1>
<h2>This is going to be a test app</h2>
<% if user_signed_in? %>
  <p>
    Now that you're authenticated, we're going to do some github tasks.
  </p>
<% else %>
  <p>
    First you're going to have to login with your github credientials.  <%= link_to "Sign in with Github", user_omniauth_authorize_path(:github) %>
  </p>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <% if flash[:notice].present? %>
    <div class="alert alert-block alert-info">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Notice!</h4>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:alert].present? %>
    <div class="alert alert-block">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Alert!</h4>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:error].present? %>
    <div class="alert alert-block alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Error!</h4>
      <%= flash[:error] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Github Programming Demo", root_path, class: "brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <% if user_signed_in? %>
            <li class="<%= "active" if controller_name == "search" %>">
              <%= link_to "Search Repos", search_index_path %>
            </li>
            <li class="<%= "active" if controller_name == "my" && action_name == "starred_repositories" %>">
              <%= link_to "My Starred Repos", my_starred_repos_path %>
            </li>
            <li class="<%= "active" if controller_name == "my" && action_name == "starred_repositories" %>">
              <%= link_to "My Recommendations", my_recommendations_path %>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path %>
            </li>
          <% else %>
            <li>
              <%= link_to "Login With Github", user_omniauth_authorize_path(:github) %>
            </li>
          <% end %>
        </ul>
      </div>
      <%= form_tag search_index_path, method: :get, class: "navbar-search pull-left", method: :get do %>
        <%= text_field_tag :keywords, params[:keywords], class: "search-query", placeholder: "Seearch Repositories", required: true %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Github Programming Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <%= render("layouts/navbar") %>
  <%= render("layouts/flash") %>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

app/views/my/recommendations.html.erb
<script>
  $(document).ready(function(){
    setInterval(function(){
      $.ajax({url: "/my/recommendations.js",
        success: function(data) {
          $("#repositories").html(data)
        },
        dataType:"html"});
    },30000);
  });
</script>


<div id="repositories">
  <% if @recommendations.present? %>
    <div class="page-header">
      <h1>Recommendations</h1>
      <p>
        <small>Last updated at <%= current_user.recommendations_generated_at.to_s(:standard) %>. (Updated every hour)</small>
      </p>
    </div>
    <%= render(partial: "shared/repos", locals: {collection: @recommendations}) %>
  <% else %>
    <h2>Loading Recommendations, this could take a while.  Please be patient.  The page will reload automatically when it is complete.</h2>
    <ul class="drops">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Loading</li>
    </ul>
  <% end %>
</div>

app/views/my/recommendations.js.erb
<% if @recommendations.present? %>
  <div class="page-header">
    <h1>Recommendations</h1>
    <p>
      <small>Last updated at <%= current_user.recommendations_generated_at.to_s(:standard) %>. (Updated every hour)</small>
    </p>
  </div>
  <%= render(partial: "shared/repos", locals: {collection: @recommendations}) %>
<% else %>
  <h2>Loading Recommendations, this could take a while.  Please be patient.  The page will reload automatically when it is complete.</h2>
  <ul class="drops blue">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Loading</li>
  </ul>
<% end %>

app/views/my/starred_repos.html.erb
<script>
  $(document).ready(function(){
    setInterval(function(){
      $.ajax({url: "/my/starred_repos.js",
        success: function(data) {
          $("#repositories").html(data)
        },
        dataType:"html"});
    },30000);
  });
</script>


<div id="repositories">
  <%= render(partial: "shared/repos", locals: {collection: @starred_repos, title: "My Starred Repositories"}) %>
</div>

app/views/my/starred_repos.js.erb
<%= render(partial: "shared/repos", locals: {collection: @starred_repos, title: "My Starred Repositories"}) %>

app/views/search/index.html.erb
<div class="row-fluid">
  <div class="span3">
    <div class="well">
      <%= form_tag search_index_path, method: :get, class: "form-search", method: :get do %>
        <div class="control-group">
          <%= label_tag :keywords, nil, class: "control-label" %>
          <div class="controls">
            <%= text_field_tag :keywords, params[:keywords], class: "search-query", placeholder: "Keywords", required: true %>
          </div>
        </div>
        <div class="control-group">
          <%= label_tag :language, nil, class: "control-label" %>
          <div class="controls">
            <%= select_tag :language, options_for_select(["JavaScript", "Ruby", "Python", "Java", "Shell", "PHP", "C", "C++", "Perl", "Objective-C"]), include_blank: true %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= submit_tag "Search Repos", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="span9">
    <h1>Search Repositories</h1>
    <% if @repos.present? && @repos.repositories.present? %>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th class="span3">Name</th>
            <th class="span3">Owner</th>
            <th class="span1">Language</th>
            <th class="span3">Description</th>
            <th class="span2">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @repos.repositories.each do |repo| %>
            <tr>
              <td><%= link_to repo.name, "http://github.com/#{repo.owner}/#{repo.name}" %></td>
              <td>
                <span class="avatar">
                  <%= link_to "http://github.com/#{repo.owner}" do %>
                    <%= repo.owner %>
                  <% end %>
                </span>
              </td>
              <td><%= repo.language %></td>
              <td><%= repo.description %></td>
              <td id="<%= "#{repo.owner}_#{repo.name}" %>">
                <% if user_signed_in? %>
                  <% if @starred_repos.any?{|starred_repo| starred_repo.full_name == "#{repo.owner}/#{repo.name}" }  %>
                    <%= link_to stars_path(user_name: repo.owner, repo_name: repo.name), class: "btn star-action" , method: :delete, remote: true, disable_with: "Loading..." do %>
                      <i class="icon-star-empty"></i> Unstar
                    <% end %>
                  <% else %>
                    <%= link_to stars_path(user_name: repo.owner, repo_name: repo.name), class: "btn star-action", remote: true, method: :post, disable_with: "Loading..." do %>
                      <i class="icon-star"></i> Star
                    <% end %>
                  <% end %>
                <% else %>
                  Please login to perform actions
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Search for repositories.  The search box should be on the left.</p>
    <% end %>
  </div>
</div>

app/views/search/users.html.erb
<div class="row-fluid">
  <div class="span3">
    <div class="well">
      <%= form_tag users_search_index_path, method: :get, class: "form-search", method: :get do %>
        <div class="control-group">
          <%= label_tag :user_name, nil, class: "control-label" %>
          <div class="controls">
            <%= text_field_tag :user_name, params[:user_name], class: "search-query", placeholder: "User Name" %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= submit_tag "Get Starred Repos", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="span9">
    <% if @starred %>
      <%= render(partial: "shared/repos", locals: {collection: @starred, title: "Search User for Starred Repositories"}) %>
    <% else %>
      <p>Search for a users' starred repositories by putting the user name in on the left</p>
    <% end %>
  </div>
</div>

app/views/shared/_repos.html.erb
<% if defined?(title) %>
  <h1><%= title %></h1>
<% end %>
<% if collection.present? %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="span3">Name</th>
        <th class="span3">Owner</th>
        <th class="span1">Language</th>
        <th class="span3">Description</th>
        <th class="span3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% collection.each do |object| %>
        <tr>
          <td><%= link_to object.repo_name, object.html_url %></td>
          <td>
            <span class="avatar">
              <%= link_to "http://github.com/#{object.owner}" do %>
                <%= image_tag(object.owner_avatar_url, height: 50, width: 50) %>
                <%= object.owner %>
              <% end %>
            </span>
          </td>
          <td><%= object.language %></td>
          <td><%= object.description %></td>
          <td id="<%= "#{object.owner}_#{object.repo_name}" %>">
            <% if user_signed_in? %>
              <% if current_user.starred_repositories.any?{|starred_repo| starred_repo.full_name == object.full_name }  %>
                <%= link_to stars_path(user_name: object.owner, repo_name: object.repo_name), class: "btn star-action" , method: :delete, remote: true, disable_with: "Loading..." do %>
                  <i class="icon-star-empty"></i> Unstar
                <% end %>
              <% else %>
                <%= link_to stars_path(user_name: object.owner, repo_name: object.repo_name), class: "btn star-action", remote: true, method: :post, disable_with: "Loading..." do %>
                  <i class="icon-star"></i> Star
                <% end %>
              <% end %>
            <% else %>
              Please login to perform actions
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Sorry, no results.</p>
<% end %>

app/views/stars/create.js.erb
$("#<%= @user_name %>_<%= @repo_name %>").html("<%= j link_to("<i class='icon-star-empty'></i> Unstar".html_safe, stars_path(user_name: @user_name, repo_name: @repo_name), class: "btn star-action" , method: :delete, remote: true, disable_with: "Loading...") %>");

app/views/stars/destroy.js.erb
$("#<%= @user_name %>_<%= @repo_name %>").html("<%=j link_to("<i class='icon-star'></i> Star".html_safe, stars_path(user_name: @user_name, repo_name: @repo_name), class: "btn star-action", remote: true, method: :post, disable_with: "Loading...") %>");